"use client";

import React, { useState } from "react";
import { ArrowRight, Check } from "lucide-react";
import { Controller, useFormContext } from "react-hook-form";

const PREDEFINED_TAGS = ["Mindset & Mental", "Relationships", "Creativity & Art", "Finance & Wealth", "Lifestyle & Order"];
const DAYS_OF_WEEK = [
  { label: "Mon", value: "MONDAY" },
  { label: "Tue", value: "TUESDAY" },
  { label: "Wed", value: "WEDNESDAY" },
  { label: "Thu", value: "THURSDAY" },
  { label: "Fri", value: "FRIDAY" },
  { label: "Sat", value: "SATURDAY" },
  { label: "Sun", value: "SUNDAY" },
];

interface Step2ParametersProps {
  onBack: () => void;
  onNext: () => void;
}

export default function Step2Parameters({ onBack, onNext }: Step2ParametersProps) {
  const { control, formState: { errors } } = useFormContext();
  const [newTagInput, setNewTagInput] = useState("");
  const [isCreatingCustomTag, setIsCreatingCustomTag] = useState(false);

  // Directly check errors object generated by Controller rules
  const isButtonDisabled = !!errors.selectedDays || !!errors.selectedTag;

  return (
    <div className="w-1/3 px-4 space-y-6">
      <h3 className="text-xs font-bold tracking-widest text-zinc-500 uppercase border-b border-zinc-900/80 pb-2">
        02 / Schedule & Category
      </h3>

      {/* DAYS SELECTION */}
      <div className="flex flex-col gap-4">
        <Controller
          control={control}
          name="selectedDays"
          rules={{ required: true, validate: (val) => val?.length > 0 }}
          render={({ field: { value = [], onChange } }) => {
            const handleDayToggle = (dayValue: string) => {
              const updatedDays = value.includes(dayValue)
                ? value.filter((d: string) => d !== dayValue)
                : [...value, dayValue];
              onChange(updatedDays);
            };

            const handleSelectDaily = () => {
              const allDays = DAYS_OF_WEEK.map((d) => d.value);
              onChange(value.length === allDays.length ? [] : allDays);
            };

            return (
              <>
                <div className="flex justify-between items-center">
                  <label className="text-sm font-medium tracking-wide text-zinc-200">
                    Which days will you commit to this habit?
                  </label>
                  <button
                    type="button"
                    onClick={handleSelectDaily}
                    className="text-[11px] px-2.5 py-1 font-medium rounded-md bg-zinc-900/80 border border-zinc-800 text-zinc-400 hover:text-zinc-200 transition-colors"
                  >
                    {value.length === DAYS_OF_WEEK.length ? "Clear All" : "Every Day"}
                  </button>
                </div>

                <div className="grid grid-cols-4 sm:grid-cols-7 gap-2 bg-zinc-900/10 p-2.5 rounded-2xl border border-zinc-900">
                  {DAYS_OF_WEEK.map((day) => {
                    const isChecked = value.includes(day.value);
                    return (
                      <button
                        key={day.value}
                        type="button"
                        onClick={() => handleDayToggle(day.value)}
                        className="flex flex-col items-center gap-2 py-2 px-1 rounded-xl transition-all hover:bg-zinc-900/20 group"
                      >
                        <div className={`w-4 h-4 rounded border flex items-center justify-center transition-all ${isChecked ? "bg-[#818CF8] border-[#818CF8]" : "border-zinc-800 bg-black"}`}>
                          {isChecked && <Check size={10} strokeWidth={3} className="text-white" />}
                        </div>
                        <span className={`text-[11px] font-semibold tracking-wide ${isChecked ? "text-[#818CF8]" : "text-zinc-500"}`}>
                          {day.label}
                        </span>
                      </button>
                    );
                  })}
                </div>
              </>
            );
          }}
        />
      </div>

      {/* CATEGORY SELECTION */}
      <div className="flex flex-col gap-4">
        <label className="text-sm font-medium tracking-wide text-zinc-200">
          What area of life does this support?
        </label>

        <Controller
          control={control}
          name="selectedTag"
          rules={{ required: true }}
          render={({ field: { value = "", onChange } }) => {
            const displayedTags = [...PREDEFINED_TAGS];
            if (value && !PREDEFINED_TAGS.includes(value)) displayedTags.push(value);

            return (
              <div className="space-y-4">
                <div className="flex flex-wrap gap-2">
                  {displayedTags.map((tagName) => {
                    const isSelected = value === tagName;
                    return (
                      <button
                        key={tagName}
                        type="button"
                        onClick={() => onChange(tagName)}
                        className={`px-3.5 h-8 text-xs rounded-full border font-medium transition-all ${isSelected ? "bg-[#818CF8] text-white border-[#818CF8]" : "bg-zinc-900/30 text-zinc-400 border-zinc-800/80"}`}
                      >
                        {tagName}
                      </button>
                    );
                  })}
                  {!isCreatingCustomTag && (
                    <button type="button" onClick={() => setIsCreatingCustomTag(true)} className="px-3 h-8 text-xs rounded-full border border-dashed border-zinc-800 text-zinc-500 font-medium">
                      + New Category
                    </button>
                  )}
                </div>

                {isCreatingCustomTag && (
                  <div className="flex gap-2 pt-1 items-center max-w-sm">
                    <input
                      placeholder="Name your category..."
                      value={newTagInput}
                      onChange={(e) => setNewTagInput(e.target.value)}
                      className="h-8 flex-1 bg-zinc-900/40 border border-zinc-800 rounded-lg px-3 text-xs text-white focus:outline-none"
                    />
                    <button type="button" onClick={(e) => { e.preventDefault(); if(newTagInput.trim()) { onChange(newTagInput.trim()); setNewTagInput(""); setIsCreatingCustomTag(false); } }} className="h-8 px-3 bg-[#818CF8] text-white text-xs font-semibold rounded-lg">
                      Add
                    </button>
                  </div>
                )}
              </div>
            );
          }}
        />
      </div>

      <div className="pt-4 flex justify-between items-center">
        <button type="button" onClick={onBack} className="text-xs font-medium text-zinc-500 hover:text-zinc-300">
          Review Step 1
        </button>
        <button
          type="button"
          onClick={onNext}
          disabled={isButtonDisabled}
          className="px-5 h-11 text-xs font-semibold bg-zinc-900 border border-zinc-800 text-zinc-200 rounded-xl disabled:opacity-20 disabled:cursor-not-allowed flex items-center gap-2"
        >
          Next Execution Details
          <ArrowRight size={14} />
        </button>
      </div>
    </div>
  );
}